### ISSUE TITLE
Add a couple of common date formatter year bugs.

### ISSUE THREAD

**Issue by calebd** [davedelong/calendar_fallacies#4] opened 2017-03-21 16:57 UTC
- `Y` vs `y` and `y` vs `yyy` or `yyyy`.
- https://twitter.com/davedelong/status/740998081542389762

**Comment by calebd** [comment] 2017-03-21 16:58
I just realized this is a subset of #1. Feel free to close.

**Comment by davedelong** [comment] 2017-03-21 17:02
Dupe of #1 

Thanks for the suggestion! 🙇

**Closed by davedelong** 2017-03-21 17:02 UTC
